// The portable skill (scripts/build-skill.mjs → dist-skill/drawcast/): it
// builds, carries the files SKILL.md promises, its frontmatter is a valid
// Agent Skill, its two link scripts agree byte for byte and round-trip, and
// every YAML it ships (the examples, SKILL.md's own skeleton) opens in the
// player the way #cast= / #paste will read it.

import { beforeAll, describe, expect, test } from "vitest";
import { spawnSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { inflateRawSync } from "node:zlib";
import { CORE_SCHEMA, load } from "js-yaml";
import { validateSpec } from "../src/spec/schema";
import { itemsOf, parsePlaylistText } from "../src/playlist/playlist";
import { ensureEnabledPacks, PACK_DEFS, DEFAULT_OFF_PACKS } from "../src/scenes/packs";

const DIST = mkdtempSync(join(tmpdir(), "drawcast-skill-"));
const SKILL = join(DIST, "drawcast");

const hasPython = spawnSync("python3", ["--version"]).status === 0;

function run(bin: string, args: string[], input?: string): string {
  const r = spawnSync(bin, args, { input, encoding: "utf8" });
  if (r.status !== 0) throw new Error(`${bin} ${args.join(" ")} failed: ${r.stderr}`);
  return r.stdout.trim();
}

function decode(link: string): string {
  const data = link.split("#cast=")[1];
  return inflateRawSync(Buffer.from(data, "base64url")).toString("utf8");
}

/** The one page a YAML text opens as, read the way the player reads it. */
function pageOf(text: string) {
  const items = itemsOf(parsePlaylistText(text));
  expect(items).toHaveLength(1);
  return items[0].spec;
}

beforeAll(async () => {
  const r = spawnSync("node", ["scripts/build-skill.mjs", DIST], { encoding: "utf8" });
  if (r.status !== 0) throw new Error(`build-skill failed:\n${r.stdout}\n${r.stderr}`);
  await ensureEnabledPacks(Object.keys(PACK_DEFS).filter((id) => !DEFAULT_OFF_PACKS.has(id)));
}, 240_000);

describe("the portable skill build", () => {
  test("writes the expected files and the zip", () => {
    for (const f of [
      "SKILL.md",
      "references/rule-card.md",
      "references/storyline.md",
      "references/look.md",
      "references/compiler.md",
      "references/sound.md",
      "references/code.md",
      "references/brief.md",
      "references/schema.json",
      "references/templates/index.md",
      "references/templates/supply_demand.md",
      "scripts/make_link.py",
      "scripts/make_link.mjs",
    ]) {
      expect(existsSync(join(SKILL, f)), f).toBe(true);
    }
    expect(existsSync(join(DIST, "drawcast-skill.zip"))).toBe(true);
    const examples = readdirSync(join(SKILL, "references/examples")).filter((f) => f.endsWith(".yaml"));
    expect(examples.length).toBeGreaterThanOrEqual(6);
    expect(examples.length).toBeLessThanOrEqual(10);
    JSON.parse(readFileSync(join(SKILL, "references/schema.json"), "utf8"));
  });

  test("SKILL.md has valid frontmatter and stays lean", () => {
    const text = readFileSync(join(SKILL, "SKILL.md"), "utf8");
    const m = /^---\n([\s\S]*?)\n---\n/.exec(text);
    expect(m).not.toBeNull();
    const fm = load(m![1], { schema: CORE_SCHEMA }) as Record<string, unknown>;
    expect(fm.name).toBe("drawcast");
    expect(typeof fm.description).toBe("string");
    expect((fm.description as string).startsWith("Use when")).toBe(true);
    expect((fm.description as string).length).toBeLessThan(1024);
    const words = text.slice(m![0].length).split(/\s+/).filter(Boolean).length;
    expect(words).toBeLessThan(2100);
  });

  test("every file SKILL.md and the references point to exists", () => {
    const skill = readFileSync(join(SKILL, "SKILL.md"), "utf8");
    for (const [, path] of skill.matchAll(/`((?:references|scripts)\/[a-z0-9_./-]+\.(?:md|json|yaml|py|mjs))`/g)) {
      expect(existsSync(join(SKILL, path)), path).toBe(true);
    }
    const refs = join(SKILL, "references");
    for (const f of readdirSync(refs).filter((f) => f.endsWith(".md"))) {
      const text = readFileSync(join(refs, f), "utf8");
      for (const [, name] of text.matchAll(/`([a-z-]+\.(?:md|json))`/g)) {
        if (name === "SKILL.md") continue;
        expect(existsSync(join(refs, name)), `${f} → ${name}`).toBe(true);
      }
    }
  });

  test("every generated file says it is generated", () => {
    const walk = (d: string): string[] => readdirSync(d, { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(join(d, e.name)) : [join(d, e.name)]));
    for (const f of walk(SKILL).filter((f) => !f.endsWith(".json"))) {
      expect(readFileSync(f, "utf8").slice(0, 1200), f).toContain("Generated by scripts/build-skill.mjs");
    }
  });

  test("every shipped example opens and validates", () => {
    const dir = join(SKILL, "references/examples");
    for (const f of readdirSync(dir)) {
      const text = readFileSync(join(dir, f), "utf8");
      expect(text).toMatch(/^# Request: /m);
      const v = validateSpec(pageOf(text));
      expect(v.errors, f).toEqual([]);
    }
  });

  test("SKILL.md's skeleton YAML opens and validates", () => {
    const text = readFileSync(join(SKILL, "SKILL.md"), "utf8");
    const block = /```yaml\n([\s\S]*?)\n```/.exec(text);
    expect(block).not.toBeNull();
    expect(validateSpec(pageOf(block![1])).errors).toEqual([]);
  });
});

describe("the link scripts", () => {
  const sample = readFileSync("scripts/skill/skeleton.yaml", "utf8");
  const unicode = "title: \"Blåbær · π ≈ 3.14 — ünïcödé\"\ncommands:\n  - speak: \"Hvorfor? 🙂\"\n";

  test("make_link.mjs round-trips (file and stdin)", () => {
    const fromFile = run("node", [join(SKILL, "scripts/make_link.mjs"), "scripts/skill/skeleton.yaml"]);
    expect(fromFile.startsWith("https://www.drawcast.app/#cast=")).toBe(true);
    expect(fromFile.split("#cast=")[1]).toMatch(/^[A-Za-z0-9_-]+$/); // base64url, no padding
    expect(decode(fromFile)).toBe(sample);
    const fromStdin = run("node", [join(SKILL, "scripts/make_link.mjs")], unicode);
    expect(decode(fromStdin)).toBe(unicode);
    expect(/^[A-Za-z0-9_-]+$/.test(fromStdin.split("#cast=")[1])).toBe(true);
  });

  test("--base points the link at another player", () => {
    const link = run("node", [join(SKILL, "scripts/make_link.mjs"), "--base", "http://localhost:5199/"], sample);
    expect(link.startsWith("http://localhost:5199/#cast=")).toBe(true);
    expect(decode(link)).toBe(sample);
  });

  test.skipIf(!hasPython)("make_link.py and make_link.mjs give byte-identical links", () => {
    for (const input of [sample, unicode, readFileSync(join(SKILL, "references/examples", readdirSync(join(SKILL, "references/examples"))[0]), "utf8")]) {
      const py = run("python3", [join(SKILL, "scripts/make_link.py")], input);
      const js = run("node", [join(SKILL, "scripts/make_link.mjs")], input);
      expect(py).toBe(js);
      expect(decode(py)).toBe(input);
    }
    expect(run("python3", [join(SKILL, "scripts/make_link.py"), "scripts/skill/skeleton.yaml"])).toBe(
      run("node", [join(SKILL, "scripts/make_link.mjs"), "scripts/skill/skeleton.yaml"]),
    );
  });
});
