// The periodic table's data shape. Generated by scripts/build-elements.mjs;
// see the header there for which fields are measured (PubChem) and which are
// derived from the atomic number by the table's own structure.

/** The ten categories a drawn table colours by. */
export type ElementCategory =
  | "nonmetal"
  | "noble-gas"
  | "alkali-metal"
  | "alkaline-earth-metal"
  | "metalloid"
  | "halogen"
  | "post-transition-metal"
  | "transition-metal"
  | "lanthanide"
  | "actinide";

export type ElementBlock = "s" | "p" | "d" | "f";

export interface ChemElement {
  z: number;
  symbol: string;
  /** `la` only where the Latin name is what explains the symbol (Fe, Na, Au…). */
  name: { en: string; nb: string; la: string | null };
  mass: number | null;
  /** 1..18, or null for the f-block, which sits in its own two rows. */
  group: number | null;
  period: number;
  block: ElementBlock;
  /** 1..15 within the lanthanide/actinide row; null outside the f-block. */
  f_index: number | null;
  category: ElementCategory;
  /** Shell order with superscripts, e.g. "[Ar]3d⁶4s²". */
  config: string;
  /**
   * Every measurement below is `null` where none has been made — 23 elements
   * have no measured electronegativity. A null must render as BLANK PAPER,
   * never as the cold end of a scale: a grey cell that reads "very low"
   * is a figure that lies.
   */
  electronegativity: number | null;
  /** Empirical atomic radius, pm. */
  radius: number | null;
  /** Melting and boiling points, K. */
  melt: number | null;
  boil: number | null;
  /** g/cm³. */
  density: number | null;
  state20: "solid" | "liquid" | "gas" | null;
  /** True for the superheavy elements whose state is computed, not observed. */
  state_predicted: boolean;
  /** A year, or "ancient" for the metals known to antiquity — its own bucket,
   *  never year zero. */
  discovered: number | "ancient" | null;
}

/** The language a drawn table writes its names in (the anatomy precedent).
 *  `la` falls back to the English name wherever no Latin name explains the
 *  symbol — which is most of the table, and is the point. */
export type ElementNameLang = "en" | "nb" | "la";

export interface ElementsEngine {
  /** All 118, in atomic-number order. */
  all(): ChemElement[];
  /** By symbol, exactly ("Fe"); case-insensitive. */
  bySymbol(symbol: string): ChemElement | null;
  /**
   * By symbol, atomic number, or a name in ANY of the three languages,
   * case-insensitively — so a spec may say "Fe", "26", "iron" or "jern"
   * and mean the same cell. The anatomy atlas resolves names the same way.
   */
  find(query: string | number): ChemElement | null;
  /** The name in the requested language, falling back to English. */
  nameIn(el: ChemElement, lang: ElementNameLang): string;
}
