// Build the PORTABLE drawcast skill: dist-skill/drawcast/ and
// dist-skill/drawcast-skill.zip — a Claude skill (or plain instructions for
// any LLM) that writes a drawcast as YAML and hands back a drawcast.app link,
// with no access to this repository.
//
//   npm run build:skill            (node scripts/build-skill.mjs [outdir])
//
// Everything is generated from the app's own sources, loaded through Vite the
// way scripts/cast.mjs loads them, so the skill never goes stale: the rule
// card (.claude/skills/drawcast/references/rule-card.md, repo-only lines
// removed), the storyline and look prompts, the compiler prompt and its sound
// and code blocks, the API schema, the template catalogue (one file per ready
// template), a handful of bundled examples as YAML, and the link scripts. The
// hand-written parts live in scripts/skill/ (SKILL.md with placeholders, the
// skeleton YAML, make_link.py/.mjs). The repo's own skill
// (.claude/skills/drawcast/) is untouched: it is the in-repo, look-and-fix
// version; this is the one anyone can load.
//
// Every generated file opens with a comment saying it is generated and from
// where. Any rewrite of an app source that no longer matches throws — the
// build fails loudly rather than shipping a repo-only instruction.

import { createServer } from "vite";
import { mkdirSync, readFileSync, rmSync, writeFileSync, chmodSync, statSync, readdirSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { spawnSync } from "node:child_process";

const ROOT = process.cwd();
const DIST = resolve(ROOT, process.argv[2] ?? "dist-skill");
const OUT = join(DIST, "drawcast");
const REPO = "github.com/hmelberg/drawcast";

/**
 * The bundled examples shipped as references/examples/<name>.yaml, by their
 * request (src/examples.json). Chosen to cover the kinds a request can take:
 * templates of different fields, an interactive template with an explore
 * beat, freehand figures (a plot with live vars, a thing with parts, a
 * count of people), one with `sources`. Each must validate and lint clean
 * (tests/build-skill.test.ts). Avoid examples whose topic is a likely trial
 * request (the sky, confidence intervals): an outsider should compose, not copy.
 */
export const EXAMPLES = [
  { name: "market-price-supply-demand", request: "If nobody sets the price, how does a market end up with one?", kind: "template `supply_demand`, animated params, a portrait cameo" },
  { name: "half-life-pk-curve", request: "How does a drug's half-life decide how often you have to take it?", kind: "template `pk_curve`" },
  { name: "epidemic-peak-sir", request: "Why does an epidemic peak before everyone is infected?", kind: "interactive template `sir_compartments`, an explore beat" },
  { name: "parabola-coefficients", request: "What do a, b and c do to a parabola?", kind: "interactive template `equation_plot`, an explore beat" },
  { name: "test-accuracy-bayes", request: "The test is 99% accurate and mine came back positive. Am I probably ill?", kind: "freehand: a grid of people, a formula that morphs" },
  { name: "ball-thrown-sideways", request: "Why does a ball thrown sideways hit the ground at the same time as one", kind: "freehand physics plot: domain, vars, trails" },
  { name: "refrigerator", request: "How does a refrigerator keep the inside cold?", kind: "freehand: a thing drawn as named parts, flow along pipes" },
  { name: "ten-thousand-steps", request: "Do you really need 10,000 steps a day?", kind: "freehand chart with `sources` and `cites`" },
];

const header = (from, style = "md") => {
  const text = `Generated by scripts/build-skill.mjs from ${from} in the drawcast repository (${REPO}). Do not edit by hand: rebuild with \`npm run build:skill\`.`;
  if (style === "md") return `<!-- ${text} -->`;
  if (style === "hash") return `# ${text}`;
  return `// ${text}`;
};

/** Replace `from` with `to` in `text`, and fail the build when `from` is not there. */
function must(text, from, to, where) {
  if (!text.includes(from)) throw new Error(`build-skill: ${where} no longer contains ${JSON.stringify(from.slice(0, 80))} — update scripts/build-skill.mjs`);
  return text.split(from).join(to);
}

/** Fail when a generated reference still points into the repo. */
function assertPortable(text, where) {
  const bad = /dev-casts|cast\.mjs|scripts\/cast|src\/llm|src\/scenes|\bgrep\b|_prompt-|references\/(course|revise|publish|pictures)\.md/.exec(text);
  if (bad) throw new Error(`build-skill: ${where} still says "${bad[0]}" — a repo-only instruction`);
}

async function withVite(fn) {
  const server = await createServer({ root: ROOT, server: { middlewareMode: true }, appType: "custom", logLevel: "error" });
  try {
    const { ensureEnabledPacks, PACK_DEFS, DEFAULT_OFF_PACKS } = await server.ssrLoadModule("/src/scenes/packs.ts");
    await ensureEnabledPacks(Object.keys(PACK_DEFS).filter((id) => !DEFAULT_OFF_PACKS.has(id)));
    return await fn((p) => server.ssrLoadModule(p));
  } finally {
    await server.close();
  }
}

const files = new Map();
const put = (path, text) => files.set(path, text.endsWith("\n") ? text : text + "\n");
const src = (p) => readFileSync(resolve(ROOT, p), "utf8");

// ---- rule card ---------------------------------------------------------------

function ruleCard() {
  const from = ".claude/skills/drawcast/references/rule-card.md";
  let t = src(from);
  const start = t.indexOf("## The page");
  if (start === -1) throw new Error(`build-skill: ${from} has no "## The page"`);
  const intro = [
    "# The compiler's rules, short (the rule card)",
    "",
    "Every tool fact the renderer depends on, in one line where one line will do,",
    "and the house taste as single lines. The teaching craft (question, insight,",
    "example, one change at a time, quiz) is the storyline's job",
    "(`storyline.md`); this card is how to STAGE it. The examples below are",
    "written as JSON objects (`{\"draw\": [\"eq\"]}`); in your YAML they are the same",
    "keys and values (`draw: [eq]`). When a field's exact shape matters, search",
    "`schema.json`; when a verb's behaviour matters, search `compiler.md`.",
    "",
    "",
  ].join("\n");
  t = intro + t.slice(start);
  t = must(t, "user gave (`url`, `look: \"screen\"`, `regions` — see references/pictures.md).", "user gave (`url`, `look: \"screen\"`, `regions` as boxes you can see — never `regions: auto`).", from);
  const sound = t.indexOf("## Sound and code");
  if (sound === -1) throw new Error(`build-skill: ${from} has no "## Sound and code"`);
  const tail = t.slice(t.indexOf("These are defaults, not laws", sound));
  t = t.slice(0, sound) + [
    "## Sound and code",
    "",
    "A drawcast about music or sound: read `sound.md` (the `play` verb, the",
    "`music` element). One that runs a script, a simulation or shows code: read",
    "`code.md` in full.",
    "",
    tail,
  ].join("\n");
  assertPortable(t, "rule-card.md");
  return `${header(from)}\n\n${t}`;
}

// ---- storyline ---------------------------------------------------------------

function storyline(treatment) {
  const from = "src/llm/prompts/treatment-v3.md and stagingNote() in src/llm/treatment.ts";
  let t = treatment.STORYLINE_PROMPT_SOURCE;
  t = must(t, "A ready template (listed below)", "A ready template (`templates/index.md`)", "treatment-v3.md");
  t = must(t, "If a template\n    in the library index (not shortlisted) would fit better, name it; its full\n    entry will be fetched.", "Read the\n    chosen template's own file (`templates/<id>.md`) before you plan beats\n    around it.", "treatment-v3.md");
  t = must(t, "Figures: ready templates (below)", "Figures: ready templates (`templates/index.md`)", "treatment-v3.md");
  const staging = treatment
    .stagingNote("", "v3")
    .split("\n")
    .filter((line) => !line.includes(treatment.TEMPLATE_GAPS_KEY))
    .map((line) => line.replace(/^## The storyline to stage$/, "## Then stage it"))
    .map((line) => line.replace("A teacher has already written this drawcast's storyline. STAGE it:", "With the storyline written, STAGE it as YAML:"))
    .map((line) => line.replace(", following your instructions;", ", following `rule-card.md`;"))
    .join("\n")
    .trim();
  const preface = [
    "In this skill you do both steps yourself: first the storyline, by the rules",
    "below (\"the next step\" is you, writing the YAML), then the staging, by the",
    "last section. Write the storyline in plain text in your working notes.",
    "",
    "",
  ].join("\n");
  const firstBreak = t.indexOf("\n\n");
  t = `${t.slice(0, firstBreak)}\n\n${preface}${t.slice(firstBreak + 2).trim()}\n\n${staging}`;
  assertPortable(t, "storyline.md");
  return `${header(from)}\n\n${t}`;
}

// ---- look --------------------------------------------------------------------

function look(compile) {
  const from = "src/llm/prompts/look-v1.md and PEDAGOGY_RUBRIC in src/llm/compile.ts";
  const lookMd = src("src/llm/prompts/look-v1.md");
  const bullets = lookMd.slice(lookMd.indexOf("- **Legibility:**"), lookMd.indexOf("House style:")).trim();
  const houseStyle = lookMd.slice(lookMd.indexOf("House style:"), lookMd.indexOf("Answer in plain text:")).trim();
  const rubric = compile.PEDAGOGY_RUBRIC.split("\n").filter((l) => /^\d+\./.test(l)).join("\n");
  if (!bullets || !houseStyle || !rubric) throw new Error("build-skill: look-v1.md or PEDAGOGY_RUBRIC changed shape");
  const t = [
    "# Self-check: look and teaching",
    "",
    "The app's reviewers read a finished drawcast against these two lists. You",
    "cannot see the frames: walk the YAML beat by beat and picture the page as",
    "it looks while each line is spoken (the canvas is 1000 × 750, 4:3). If the",
    "user sends a screenshot of the player, judge it by the first list.",
    "",
    "## How it looks (the visual reviewer's list)",
    "",
    bullets,
    "",
    houseStyle,
    "",
    "Fixes change the drawing and the staging, not the spoken lines, unless a",
    "line contradicts the picture. \"Remove X\" (or \"erase X after beat N\") is",
    "often the best fix.",
    "",
    "## How it teaches (the teacher's list)",
    "",
    rubric,
  ].join("\n");
  assertPortable(t, "look.md");
  return `${header(from)}\n\n${t}`;
}

// ---- the compiler prompt, sound, code ---------------------------------------------

function compilerRef(compile) {
  const from = "src/llm/prompts/compiler-v1.md";
  let t = compile.promptVariants().find((v) => v.name === "v1")?.source;
  if (!t) throw new Error("build-skill: no compiler-v1 prompt");
  t = t.slice(0, t.indexOf("## Output"));
  t = must(t, "{{SOUND}}", "(The `play` verb and the `music` element: `sound.md`.)", from);
  t = must(t, "{{CODE}}", "- **code** (a script that runs and draws its output): `code.md`.", from);
  t = must(
    t,
    "the app maps a picture URL in the request for you: use the part names it lists (write `\"regions\": \"auto\"` on the image; the boxes are filled in); without a list, only boxes the user gave",
    "nothing maps the picture for you here: write boxes only for parts you can see in it yourself, or boxes the user gave, and never `\"regions\": \"auto\"`",
    from,
  );
  t = must(t, "Only the output contract is absolute: a valid spec, JSON only.", "Only the output contract is absolute: a valid spec.", from);
  const preface = [
    "<!-- The app's full compiler prompt, for looking a verb or an element up.",
    "     Written for the app's one-shot generator: where it says JSON, write the",
    "     same keys and values as YAML; its schema is schema.json, its catalogue",
    "     templates/, and its examples are examples/. -->",
  ].join("\n");
  assertPortable(t, "compiler.md");
  return `${header(from)}\n${preface}\n\n${t.trim()}`;
}

function soundRef(compile) {
  const from = "src/llm/prompts/compiler-v1-sound.md";
  const t = ["# Sound and music", "", "Only when the figure is genuinely about sound or music. Examples are JSON; write the same in YAML.", "", compile.SOUND_PROMPT_SOURCE.trim()].join("\n");
  assertPortable(t, "sound.md");
  return `${header(from)}\n\n${t}`;
}

function codeRef(compile) {
  const from = "src/llm/prompts/compiler-v1-code.md";
  const t = ["# Code on the page", "", "For a drawcast that runs a script (a simulation, a computed chart, a lesson about code). Examples are JSON; write the same in YAML — a multi-line script as a `|` block.", "", compile.CODE_PROMPT_SOURCE.trim()].join("\n");
  assertPortable(t, "code.md");
  return `${header(from)}\n\n${t}`;
}

// ---- brief -------------------------------------------------------------------------

function briefLines(briefControls) {
  const defaults = { audience: "curious adults of better-than-average ability with decent general knowledge, but no special knowledge of this topic", level: "standard", length: "14–20 spoken lines" };
  return briefControls.BRIEF_CONTROLS.map((c) => {
    const def = c.options.find((o) => o.value === "");
    const others = c.options.filter((o) => o.value && o.value !== "for").map((o) => `\`#${o.value}\` ${o.label.toLowerCase()} (${o.hint.replace(/^./, (x) => x.toLowerCase())})`);
    if (c.options.some((o) => o.value === "for")) others.push("`#for=<who>` anyone else (`#for=nurses`)");
    const d = c.group === "level" ? `\`standard\` — ${def.hint.replace(/^./, (x) => x.toLowerCase())}` : c.group === "length" ? def.hint : defaults.audience;
    return `- **${c.label}:** ${d}. Others: ${others.join("; ")}.`;
  }).join("\n");
}

function briefRef(tags) {
  const from = "src/llm/tags.ts";
  const groups = new Map();
  for (const def of tags.TAGS) {
    if (!groups.has(def.group)) groups.set(def.group, []);
    groups.get(def.group).push(def);
  }
  const lines = [
    "# The request's tags",
    "",
    "The app's request box understands these hashtags; a user may type them in a",
    "request to you too, or say the same in words. Each tag adds the brief shown",
    "under it to your instructions. Tags in one group exclude each other (the",
    "last one wins). A tag that asks for something the rest of this skill does",
    "not cover (a playlist of several parts) — do the nearest single drawcast and",
    "say so.",
    "",
  ];
  for (const [group, defs] of groups) {
    lines.push(`## ${group}`, "");
    for (const d of defs) {
      const names = [d.tag, ...(d.aliases ?? [])].map((n) => `\`#${n}\``).join(", ");
      lines.push(`- ${names} — ${d.hint}${d.brief ? `\n  ${d.brief}` : ""}`);
    }
    lines.push("");
  }
  lines.push(`Shared by the reality tags: ${tags.GUARDRAIL}`, "", `Shared by the tone tags: ${tags.RESTRAINT}`);
  return `${header(from)}\n\n${lines.join("\n")}`;
}

// ---- templates ---------------------------------------------------------------------

function firstSentence(d) {
  const m = /^[^.!?]*[.!?]/.exec(d.trim());
  return (m ? m[0] : d.trim()).trim();
}
function chooseSentence(d) {
  const m = /\b(?:Choose|Use|Pick) this[^.!?]*[.!?]/.exec(d);
  return m ? m[0].trim() : null;
}

function templates(catalog, scenes, packs) {
  const ready = Object.values(scenes).filter((s) => s.manifest.status === "ready" && catalog.isReadyTemplate(s.manifest.name));
  const index = [
    header("the scene registry (src/scenes, catalogParts in src/scenes/catalog.ts)"),
    "",
    "# The templates",
    "",
    `${ready.length} ready templates. A template draws an exact, good-looking figure from a few`,
    "`params` and names its parts, so your commands can draw, highlight and",
    "animate them. Use one when it can tell THIS story (`template: <id>` +",
    "`params:`); otherwise build the figure freehand from elements (`rule-card.md`).",
    "Before using one, read its own file, `templates/<id>.md`: its parameter",
    "schema, its element ids, and example params. \"Viewer can\" is what the viewer",
    "can do with it while paused — plan an explore beat around it.",
    "",
  ];
  // Grouped by field (the app's packs), the built-in templates first.
  const byId = new Map(ready.map((s) => [s.manifest.name, s.manifest]));
  const groups = [];
  const packed = new Set();
  for (const def of Object.values(packs.PACK_DEFS)) {
    const ids = packs.packTemplateIds(def.id).filter((id) => byId.has(id) && !packed.has(id));
    ids.forEach((id) => packed.add(id));
    if (ids.length) groups.push({ title: def.title, ids });
  }
  groups.unshift({ title: "General", ids: [...byId.keys()].filter((id) => !packed.has(id)) });
  const out = {};
  for (const g of groups) {
    index.push(`## ${g.title}`, "");
    for (const id of g.ids) {
      const m = byId.get(id);
      const choose = chooseSentence(m.description);
      const first = firstSentence(m.description);
      index.push(`- **${m.name}**: ${first}${choose && choose !== first ? ` ${choose}` : ""}${m.interaction ? `\n  Viewer can: ${m.interaction}` : ""}`);
    }
    index.push("");
  }
  for (const { manifest: m } of ready) {    let entry = catalog.catalogParts({ forced: m.name }).stable;
    entry = must(entry, `\n\nYou MUST set "template" to "${m.name}" for this request.`, "", `the catalog entry of ${m.name}`);
    entry = entry.replace(/^### Scene template: (\S+) \(READY — prefer this when it fits\)/, "# Template: $1");
    const lines = [
      header(`the ${m.name} manifest (catalogParts in src/scenes/catalog.ts)`),
      "",
      entry.trim(),
    ];
    if (m.interaction) lines.push("", `Viewer can: ${m.interaction}`);
    lines.push("", `In YAML: \`template: ${m.name}\` and \`params:\` per the schema above; commands name the element ids above.`);
    out[m.name] = lines.join("\n");
  }
  return { index: index.join("\n"), entries: out, count: ready.length };
}

// ---- examples ----------------------------------------------------------------------

function examples(text, validate) {
  const all = JSON.parse(src("src/examples.json"));
  const out = [];
  for (const ex of EXAMPLES) {
    const found = all.filter((e) => !e.specimen && e.spec && e.request.startsWith(ex.request));
    if (found.length !== 1) throw new Error(`build-skill: example "${ex.request}" matches ${found.length} entries of src/examples.json`);
    const { spec, request } = found[0];
    const v = validate(spec);
    if (!v.ok) throw new Error(`build-skill: example ${ex.name} is invalid: ${v.errors.join("; ")}`);
    const yaml = text.dumpSpecYaml(spec);
    const body = [
      header("src/examples.json", "hash"),
      `# Request: ${request.replace(/\s+/g, " ")}`,
      `# Shows: ${ex.kind.replace(/`/g, "")}`,
      yaml,
    ].join("\n");
    out.push({ ...ex, file: `${ex.name}.yaml`, body });
  }
  return out;
}

// ---- SKILL.md ---------------------------------------------------------------------

function skillMd({ brief, count, exampleRows }) {
  let t = src("scripts/skill/SKILL.md");
  const skeleton = src("scripts/skill/skeleton.yaml").trimEnd();
  t = must(t, "{{HEADER}}", header("scripts/skill/SKILL.md"), "SKILL.md");
  t = must(t, "{{BRIEF}}", brief, "SKILL.md");
  t = must(t, "{{TEMPLATE_COUNT}}", String(count), "SKILL.md");
  t = must(t, "{{EXAMPLES}}", exampleRows, "SKILL.md");
  t = must(t, "{{SKELETON}}", skeleton, "SKILL.md");
  if (/\{\{[A-Z_]+\}\}/.test(t)) throw new Error("build-skill: SKILL.md has an unfilled placeholder");
  assertPortable(t, "SKILL.md");
  return t;
}

function linkScript(name, style) {
  const from = `scripts/skill/${name}`;
  const t = src(from);
  const nl = t.indexOf("\n");
  // The shebang stays first; the generated note follows it.
  return `${t.slice(0, nl)}\n${header(from, style)}\n${t.slice(nl + 1)}`;
}

// ---- build ------------------------------------------------------------------------

export async function buildSkill() {
  await withVite(async (load) => {
    const compile = await load("/src/llm/compile.ts");
    const catalog = await load("/src/scenes/catalog.ts");
    const { scenes } = await load("/src/scenes/registry.ts");
    const treatment = await load("/src/llm/treatment.ts");
    const tags = await load("/src/llm/tags.ts");
    const briefControls = await load("/src/llm/brief-controls.ts");
    const text = await load("/src/spec/text.ts");
    const { validateSpec } = await load("/src/spec/schema.ts");

    const tpl = templates(catalog, scenes, await load("/src/scenes/packs.ts"));
    const exs = examples(text, validateSpec);
    const exampleRows = ["| File | Request | Shows |", "|---|---|---|", ...exs.map((e) => `| \`references/examples/${e.file}\` | ${e.request.replace(/\|/g, "/")}${e.request.endsWith("?") ? "" : "…"} | ${e.kind} |`)].join("\n");

    put("SKILL.md", skillMd({ brief: briefLines(briefControls), count: tpl.count, exampleRows }));
    put("references/rule-card.md", ruleCard());
    put("references/storyline.md", storyline(treatment));
    put("references/look.md", look(compile));
    put("references/compiler.md", compilerRef(compile));
    put("references/sound.md", soundRef(compile));
    put("references/code.md", codeRef(compile));
    put("references/brief.md", briefRef(tags));
    // The full schema (code and sound included): the file is read on demand,
    // so there is no prompt budget to gate it for.
    put("references/schema.json", JSON.stringify(compile.apiSchema(), null, 1));
    put("references/templates/index.md", tpl.index);
    for (const [id, body] of Object.entries(tpl.entries)) put(`references/templates/${id}.md`, body);
    for (const e of exs) put(`references/examples/${e.file}`, e.body);
    put("scripts/make_link.py", linkScript("make_link.py", "hash"));
    put("scripts/make_link.mjs", linkScript("make_link.mjs", "slash"));
  });

  rmSync(OUT, { recursive: true, force: true });
  for (const [path, body] of files) {
    const at = join(OUT, path);
    mkdirSync(dirname(at), { recursive: true });
    writeFileSync(at, body);
  }
  chmodSync(join(OUT, "scripts/make_link.py"), 0o755);
  chmodSync(join(OUT, "scripts/make_link.mjs"), 0o755);

  // The zip holds the folder itself (drawcast/SKILL.md …), the layout a skill upload expects.
  const zip = join(DIST, "drawcast-skill.zip");
  rmSync(zip, { force: true });
  const r = spawnSync("zip", ["-qrX", zip, "drawcast"], { cwd: DIST, stdio: "inherit" });
  if (r.status !== 0) throw new Error("build-skill: zip failed (is the zip command installed?)");
  return { out: OUT, zip, files: [...files.keys()] };
}

function tree(dir) {
  const rows = [];
  const walk = (d) => {
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else rows.push(`${String(statSync(p).size).padStart(8)}  ${relative(dir, p)}`);
    }
  };
  walk(dir);
  return rows;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { out, zip, files: list } = await buildSkill();
  const rows = tree(out);
  const templatesCount = list.filter((f) => f.startsWith("references/templates/") && !f.endsWith("index.md")).length;
  console.log(rows.filter((r) => !/references\/templates\/(?!index)/.test(r)).join("\n"));
  console.log(`   (+ ${templatesCount} files references/templates/<id>.md)`);
  console.log(`${relative(ROOT, out)}: ${list.length} files · ${relative(ROOT, zip)}: ${statSync(zip).size} bytes`);
}
